site_name: Cancer Prediction
site_url: https://github.com/bharding11/cancer-prediction-bjh70
repo_url: https://github.com/bharding11/cancer-prediction-bjh70
nav:
  - Home: index.md
  - cancer-prediction:
    - cancer model: cancer-prediction-bjh70/cancer_model.md
    - streamlit app: cancer-prediction-bjh70/streamlit_app.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for file changes